blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

NULLABLE = {"blank": "True", "null": "True"}


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name="заголовок")
    slug = models.CharField(max_length=150, verbose_name='URL', **NULLABLE)
    content = models.TextField(verbose_name="содержимое", **NULLABLE)
    preview = models.ImageField(upload_to='blog/photo', **NULLABLE, verbose_name='Превью')
    created_at = models.DateField(default=timezone.now, auto_created=True, verbose_name="дата создания")
    published = models.BooleanField(default=True, verbose_name='опубликован')
    views = models.IntegerField(default=0, verbose_name='просмотры')

blog/views.py
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from blog.functions.utils import send_email
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'created_at')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'slug', 'content', 'preview', 'created_at')

    def form_valid(self, form):
        if form.is_valid():
            new_data = form.save()
            new_data.slug = slugify(new_data.title)
            new_data.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()

        if self.object.views == 100:
            send_email(self.object)

        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kekstore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
{% include 'blog/includes/inc_main_menu.html' %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Kekstore</h1>

    <p class="lead">Kekstore - лучший продовольственный магазин, в котором вы найдёте всё самое свежее</p>


</div>

<div class="container">




    {% block content %}
    {% endblock %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row text-center">
            <div class="col-3 col-md">
                Kekstore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-3 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление продукта</h4>
            </div>
            <div class="card-text">Вы действительно хотите удалить продукт {{object.name}} ?</div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                    {% csrf_token %}




                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Удалить
                    </button>

                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:list' %}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>




{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                Материал {{object.title}} {{object.slug}}
                <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                <h4 class="my-0 font-weight-normal">{{ object.content }}</h4>
                <h4 class="my-0 font-weight-normal">{{ object.slug }}</h4>
            </div>
             <div class="card-body">
                <img src="{{object.preview|media_filter}}" class="card-img-top" alt={{object.preview|media_filter}}>

            </div>

            <div class="card-body">
                <a class="btn btn-primary" role="button"
                   href="{% url 'blog:list' %}">Назад</a>
            </div>
            Просмотры: {{object.views}}
        </div>

    </div>
    {% endblock %}
</div>

blog/templates/blog/blog_form.html
{% extends 'blog/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Добавить новую статью</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                    {% csrf_token %}
                    {{form.as_p}}



                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-info">
                        {% if object %}
                        Изменить
                        {% else %}
                        Создать
                        {% endif %}


                    </button>
                </form>
            </div>
        </div>
    </div>
</div>




{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}


<div class="row text-right">
    {% for object in object_list %}

    <div class="col-4">

        <div class="card mb-3 box-shadow">
            <img src="{{ object.preview | media_filter }}" class="card-img-top" alt={{object.preview|media_filter}}>


            <div class="card-body">
                <h5 class="card-title">
                    <div style="color: blue"><b>{{object.title}}</b></div>
                </h5>
                <p class="card-text">
                    {% if object.content|length >= 100 %}
                    {{ object.content|slice:":100"}} ...
                    {% else %}
                    {{ object.content}}
                    {% endif %}
                </p>
                <div class="btn-group">
                    <a class="btn btn-link" href="{% url 'blog:view' object.pk%}" role="button">Посмотреть</a>


                    <a class="btn btn-info" href="{% url 'blog:edit' object.pk%}"
                       role="button">Изменить</a>

                    <a class="btn btn-danger" href="{% url 'blog:delete' object.pk%}"
                       role="button">Удалить</a>
                </div>

            </div>

    </div>


    </div>
    {% endfor %}

</div>
</div>


{% if is_paginated %}

<div class="col-12">
    <div class="card mb-3 box-shadow">

        <div class="card-body">

            <div class="btn-group">


                <ul class="pagination">
                    {% if page_obj.has_previous %}


                    <li>

                        <a class="p-2 btn btn-outline-primary"
                           href="?page={{ page_obj.previous_page_number }}"
                           role="button"> &laquo; </a> &nbsp;


                    </li>
                    {% else %}

                    <li class="disabled p-2 btn btn-outline-primary" role="button"><span>&laquo;</span></li> &nbsp;
                    {% endif %}


                    {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                    <li class="disabled p-2 btn btn-outline-primary" role="button"><span>{{ i }}(текущая);</span></li>
                    &nbsp;
                    {% else %}
                    <li>


                        <a class="p-2 btn btn-outline-primary"
                           href="?page={{ i }}"
                           role="button"> {{ i }} </a> &nbsp;

                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li>

                        <a class="p-2 btn btn-outline-primary"
                           href="?page={{ page_obj.next_page_number }}"
                           role="button"> &raquo; </a>

                    </li>
                    {% else %}
                    <li class="disabled p-2 btn btn-outline-primary" role="button"><span>&raquo; </span></li> &nbsp;
                    {% endif %}
                </ul>

            </div>

        </div>
    </div>
</div>

{% endif %}


</div>

{% endblock %}