blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import ProductListView, ProductDetailView, ContactListView, OrderCreateView, ProductUpdateView, \
    ProductDeleteView, VersionListView, VersionDetailView, VersionCreateView, VersionUpdateView, VersionDeleteView, \
    ProductCreateView

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('contacts/', ContactListView.as_view(), name='contacts'),
    path('create_order/', OrderCreateView.as_view(), name='create_order'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("versions/", VersionListView.as_view(), name="versions"),
    path("versions/<int:pk>/", VersionDetailView.as_view(), name="version_detail"),
    path("create_version/", VersionCreateView.as_view(), name="version_create"),
    path("version/<int:pk>/update/", VersionUpdateView.as_view(), name="version_update"),
    path("version/<int:pk>/delete/", VersionDeleteView.as_view(), name="version_delete"),
]

main/models.py
from django.db import models
from django.utils import timezone

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    """
    Модель Category
    :param:
    - Имя name
    - Описание description
    """
    name = models.CharField(max_length=250, verbose_name='Название', help_text="Введите название категории", )
    description = models.TextField(verbose_name='Описание', **NULLABLE, help_text="Введите описание категории", )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    """
    Модель Product
    :param:
    - Имя name
    - Описание description
    - Изображение (превью) preview
    - Категория category
    - Цена за покупку price
    - Дата создания (записи в БД) created_at
    - Дата последнего изменения (записи в БД) updated_at
    """
    name = models.CharField(max_length=250, verbose_name='Наименование', help_text="Введите наименование", )
    description = models.TextField(verbose_name='Описание', **NULLABLE, help_text="Введите описание", )
    preview = models.ImageField(upload_to='product/photo', **NULLABLE, verbose_name='Превью',
                                help_text="Загрузите изображение", )
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория',
                                 help_text="Введите категорию", related_name="categories", )
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена', help_text="Введите цену", )
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания',
                                      help_text="Введите дату создания", )
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения',
                                      help_text="Введите дату изменения", )

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ["category", "name"]


class Contact(models.Model):
    """
    Модель Contact
    :param:
    - Название подразделения и/или контактное лицо name
    - Телефон phone:
    - ИНН inn
    - Адрес address
    """
    name = models.CharField(max_length=50, verbose_name="Название/Имя",
                            help_text="Введите название подразделения или укажите контактное лицо", )
    phone = models.CharField(max_length=20, verbose_name="Телефон", help_text="Введите телефон", )
    inn = models.CharField(default="Не указан", max_length=12, verbose_name="ИНН", help_text="Введите ИНН", )
    address = models.CharField(default="Не указан", max_length=100, verbose_name="Адрес", help_text="Введите адрес", )

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

    def __str__(self):
        return f"{self.name} \n{self.phone} \n{self.inn} \n{self.address}"


class Order(models.Model):
    """
    Модель Order
    :param:
    - Имя name
    - Телефон phone:
    - Сообщение message
    - Дата отправки created_at
    """
    name = models.CharField(max_length=50, verbose_name="Имя", help_text="Введите имя", )
    phone = models.CharField(max_length=20, verbose_name="Телефон", help_text="Введите телефон", )
    message = models.TextField(verbose_name="Сообщение", help_text="Введите сообщение", **NULLABLE)
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата отправки",
                                      help_text="Введите дату создания", )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return f"{self.name} - {self.phone} \n {self.created_at} \n {self.message}"


class Version(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE,
                                verbose_name="продукт",
                                help_text="название продукта",
                                related_name="product",
                                )
    number = models.PositiveIntegerField(
        verbose_name="Номер версии",
        help_text="укажите номер версии",
    )
    name = models.CharField(
        max_length=100,
        verbose_name="Название версии",
        help_text="Введите название версии",
    )
    sign = models.BooleanField(
        verbose_name="Признак текущей версии")

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["number", "name"]

    def __str__(self):
        return f"{self.number}-{self.name}:{self.sign}"

main/forms.py
from django import forms
from django.forms import BooleanField

from main.models import Product, Contact, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def clean(self):
        blacklist = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        cleaned_data = self.cleaned_data['name'] + self.cleaned_data['description']

        for b_word in blacklist:
            if b_word in cleaned_data:
                raise forms.ValidationError(
                    'Нельзя использовать запретки (ладно, можно, но не все)')

        else:
            return self.cleaned_data


class ContactForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

main/views.py
from django.forms import inlineformset_factory
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main.forms import ProductForm, VersionForm
from main.models import Product, Contact, Order, Version


class GetContextMixin:
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['version'] = Version.objects.all()
        return context_data


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("main:product_list")


class ProductListView(GetContextMixin, ListView):
    model = Product


class ProductDetailView(GetContextMixin, DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['title'] = self.object.name
        return context


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:product_list')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('main:product_list')


class ContactListView(ListView):
    model = Contact


class OrderCreateView(CreateView):
    model = Order  # Модель
    fields = ('name', 'phone', 'message', 'created_at')  # Поля для заполнения при создании
    success_url = reverse_lazy('main:product_list')  # Адрес для перенаправления после успешного создания

    def form_valid(self, form):
        form.instance.author = self.request.user
        response = super().form_valid(form)
        return response


class VersionListView(ListView):
    model = Version


class VersionDetailView(DetailView):
    model = Version


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy("main:versions")


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy("main:versions")


class VersionDeleteView(DeleteView):
    model = Version
    success_url = reverse_lazy("main:versions")

main/templates/main/base.html
<!doctype html>
{% load static %}
{% load my_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kekstore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
</head>
<body>

{% include 'main/includes/inc_main_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Kekstore</h1>
    <p class="lead">Kekstore - лучший продовольственный магазин, в котором вы найдёте всё самое свежее</p>
</div>

{% block content %}
    {% endblock %}

<div class="container">
<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                KekStore
                <small class="d-block mb-3 text-muted">&copy; {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
    </div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}">
</script>
</body>
</html>

main/templates/main/contact_list.html
{% extends 'main/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        {% for object in object_list %}

                        <tr>
                            <td class="w-25">Отдел/ контактное лицо</td>
                            <td>{{object.name}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{object.inn}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{object.address}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Контактный номер</td>
                            <td>{{object.phone}}</td>
                            </tr>
                        <tr>
                            <td class="w-25"></td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="col-12 mb-5">
                    <a class="btn btn-outline-primary" href="{% url 'main:create_order' %}">Отправить сообщение</a>
                </div>
    </div>


</div>

{% endblock %}

main/templates/main/contacts.html
{% extends 'main/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        {% for object in object_list %}

                        <tr>
                            <td class="w-25">Отдел/ контактное лицо</td>
                            <td>{{object.name}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{object.inn}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{object.address}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Контактный номер</td>
                            <td>{{object.phone}}</td>
                            </tr>
                        <tr>
                            <td class="w-25"></td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Напишите сюда..." required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


</div>

{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                 <img src="{{ object.preview | media_filter }}" class="card-img-top" alt={{object.name}}>
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object | title}}</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">{{ object.price}} руб./кг</h3>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <p class="card-text">
                    {% if object.description|length >= 100 %}
                    {{ object.description|slice:":100"}} ...
                    {% else %}
                    {{ object.description}}
                    {% endif %}
                            </p>
                    </ul>
                    <a href="{% url 'main:product_pk' object.pk %}" class="card-link">Ссылка на товар</a>
                    <button type="button"  class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>


{% endblock %}

main/templates/main/order_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn-success">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление продукта</h4>
            </div>
            <div class="card-body">

                <div class="card-text">Вы действительно хотите удалить продукт {{object.name}} ?</div>
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                        {% csrf_token %}


                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Удалить
                    </button>

                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'main:product_list' %}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}

<div class="row text-right">
    <div class="col-6">
        <div class="card mb-3 box-shadow">

            <div class="card-body">
                <img src="{{object.preview |media_filter}}" class="card-img-top" alt={{object.name}}>

            </div>
        </div>

    </div>


    <div class="col-6">

        <div class="card mb-3 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Информация</h4>
            </div>


            <div class="card-body">
                <h5 class="card-title">
                    <div style="color: black"><b>{{object | title}}</b></div>
                </h5>
                <p class="card-text">


                <br>
                <b>Наименование: </b>{{object.name}}
                <br> <br>
                <b>Описание: </b>{{object.description}}
                <br> <br>
                <b>Категория: </b>{{object.category}}
                <br> <br>
                <b>Цена: </b>{{object.price}}
                <br><br>
                <small class="text-body-secondary">

                    Последний привоз: {{object.created_at}}
                    <br>
                    Наличие уточнять на складе :))0)


                </small>


                </p>
                <div class="btn-group">

                    <a class="btn btn-primary" href="{% url 'main:product_list' %}" role="button"> Вернуться на главную
                        страницу </a>



                </div>


            </div>
        </div>


    </div>


</div>

{% endblock %}

main/templates/main/product_form.html
{% extends 'main/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Добавить свой продукт</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                        {% csrf_token %}
                        {{form.as_p}}


                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                        Изменить
                        {% else %}
                        Создать
                        {% endif %}


                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                 <img src="{{ object.preview | media_filter }}" class="card-img-top" alt={{object.name}}>
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object | title}}</h4>
                </div>
                <div class="card-body">
                    <h3 class="card-title pricing-card-title">{{ object.price}} руб./кг</h3>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <p class="card-text">
                    {% if object.description|length >= 100 %}
                    {{ object.description|slice:":100"}} ...
                    {% else %}
                    {{ object.description}}
                    {% endif %}
                            </p>
                    </ul>


                    <a class="btn btn-primary" href="{% url 'main:product_detail' object.pk%}"
                       role="button">Подробнее</a>

                    <a class="btn btn-primary" href="{% url 'main:product_update' object.pk%}"
                       role="button">Изменить</a>

                    <a class="btn btn-primary" href="{% url 'main:product_delete' object.pk%}"
                       role="button">Удалить</a>

                </div>
                <button type="button"  class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            </div>
        </div>

        {% endfor %}

    </div>


{% endblock %}

main/templates/main/product_pk.html
{% extends 'main/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}

<div class="row text-right">
    <div class="col-6">
        <div class="card mb-3 box-shadow">

            <div class="card-body">
                <img src="{{object.preview |media_filter}}" class="card-img-top" alt={{object.name}}>

            </div>
        </div>

    </div>


    <div class="col-6">

        <div class="card mb-3 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Информация</h4>
            </div>


            <div class="card-body">
                <h5 class="card-title">
                    <div style="color: black"><b>{{object | title}}</b></div>
                </h5>
                <p class="card-text">


                <br>
                <b>Наименование: </b>{{object.name}}
                <br> <br>
                <b>Описание: </b>{{object.description}}
                <br> <br>
                <b>Категория: </b>{{object.category}}
                <br> <br>
                <b>Цена: </b>{{object.price}}
                <br><br>
                <small class="text-body-secondary">

                    Последний привоз: {{object.created_at}}
                    <br>
                    Наличие уточнять на складе :))0)


                </small>


                </p>
                <div class="btn-group">

                    <a class="btn btn-primary" href="{% url 'main:home' %}" role="button"> Вернуться на главную
                        страницу </a>



                </div>


            </div>
        </div>


    </div>


</div>

{% endblock %}

main/templates/main/version_confirm_delete.html
{% extends 'main/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Удаление продукта</h4>
            </div>
            <div class="card-body">

            <div class="card-text">Вы действительно хотите удалить версию продукта {{object.name}} ?</div>
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                    {% csrf_token %}

                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Удалить
                    </button>

                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'main:versions' %}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}

main/templates/main/version_detail.html
{% extends 'main/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}

<div class="row text-right">

    <div class="col-12">

        <div class="card mb-3 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Информация о версии</h4>
            </div>


            <div class="card-body">
                <h5 class="card-title">
                    <div style="color: orange"><b>{{object | title}}</b></div>
                </h5>
                <p class="card-text">
                    <b>Продукт:</b> &nbsp; {{ object.product }}<br>


                    <b>Номер версии:</b> &nbsp; {{ object.number }}<br>
                    <b>Название версии:</b> &nbsp; {{ object.name }}<br>
                    <b>Признак актуальности:</b> &nbsp; {{ object.sign }}<br>


                </p>
                <div class="btn-group">

                    <a class="btn btn-primary" href="{% url 'main:product_update' object.pk%}"
                       role="button">Изменить</a>
                    <a class="btn btn-primary" href="{% url 'main:product_delete' object.pk%}"
                       role="button">Удалить</a>

                    <a class="btn btn-primary" href="{% url 'main:versions' %}"
                       role="button">К списку версий продуктов</a>


                </div>


            </div>
        </div>


    </div>


</div>

{% endblock %}>

main/templates/main/version_list.html
{% extends 'main/base.html'%}
{% load static %}
{% load my_tags %}
{% block content %}


<div class="row text-right">
    <div class="col-12">

        <div class="card mb-3 box-shadow">
            <div class="card-body">
                <a class="btn btn-primary" href="{% url 'main:version_create' %}" role="button">Создать версию
                    продукта</a>
                <br><br>


                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Номер версии</th>
                        <th scope="col">Название</th>
                        <th scope="col">Продукт</th>
                        <th scope="col">Актуальность</th>
                        <th scope="col">info btn</th>
                        <th scope="col">change btn</th>
                        <th scope="col">del btn</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% load my_tags %}


                    {% for object in object_list %}

                    <tr>
                        <td>{{ object.number }}</td>
                        <td>{{ object.name }}</td>
                        <td>{{ object.product}}</td>
                        <td>{{ object.sign }}</td>
                        <td><a class="btn btn-primary" href="{% url 'main:version_detail' object.pk%}"
                               role="button">Посмотреть</a></td>

                        <td><a class="btn btn-primary" href="{% url 'main:version_update' object.pk%}" role="button">Изменить</a>
                        </td>
                        <td><a class="btn btn-primary" href="{% url 'main:version_delete' object.pk%}" role="button">Удалить</a>
                        </td>

                    </tr>
                    {% endfor %}

                    </tbody>
                </table>


            </div>
        </div>


    </div>


</div>


{% endblock %}